### ISSUE TITLE
Handle empty dates

### ISSUE THREAD

**Issue by ahalterman** [oudalab/fajita#105]
When actors are still in office or in a role, the end state should be blank. (And this also happens with start dates, too). If they're left blank, the system currently fills in some other date (today's?), which is not what we want. 

Instead, coders should add some special code (maybe NA) when no date should be coded. Then, on the backend, that NA code can be converted into a blank or whatever character we need. 

- [ ] Front end and back end need to handle the special code
- [ ] Coders need to be instructed on the special code to use

**Comment by manarlandis** [comment]
1-	Need to clear all fields (clear button is not enough, still making mistakes), this might be done if you clear the upper row of (country, primary role, and secondary role) because they keep the previous data even if coders move to the next noun while second row clears everything. 
3-	Search takes too long (13 seconds)
4-	Need dates on flagged verbs
5-	There are some codes without coder's name on pages 29, 30, 32,34,....  (That was before we lost the data. I will keep an eye to see if it still happens)   
6-	Ending date is not blank when it should be. This confuses me when I need to know if the coder made a mistake or not (we discussed to day and Andy listed the solution suggested by Yan) 
8-	if coder pushes “commit” multiple times, the system will save their committed work several times. This gives false information about the number of coding that each coder did   
9-	needs to have a feature where I could search for the work for each coder.  Overlapping coding times by more than one coder, where they work at the same time, makes monitoring each coder work and analyzing the coding data take long time. I need to evaluate the time the each coders take every week to accomplish certain number of codes.

**Comment by YanLiang1102** [comment]
#118 
@ahalterman ,@manarlandis  this should be fixed , so now 
how the app do it is 
1.if you put in "na" or empty in datePicker input, it will translate that into "1800-01-01" 
(sicne it has to be a dateformat like this in order to be stored in the db"
and when the template render this on the brower, it will translate that into "na"
2.similar thing for "now" {which means until now or present role") if you put this in the datepicker input,
it will translated into "2200-01-o1" and later it will be translated into "now" on the webpage
Will attach an example here

**Comment by YanLiang1102** [comment]
![image](https://cloud.githubusercontent.com/assets/10291607/22449942/d3906534-e728-11e6-827d-604342741ce4.png)
