### ISSUE TITLE
Interface stopped saving "nouns"

### ISSUE THREAD

**Issue by manarlandis** [oudalab/fajita#111]
Coders can't save their "noun" coding after working for period of time (some after 30 minutes, or 2 hours, and after 4 hours.) Interface worked just fine then stopped saving nouns for no obvious reason. coders opened interface from different program (Safari, Firefox, Chrome), in which it worked for couple of hours then quit saving again.

**Comment by cegme** [comment]
@yanliang1102 can you increase the lifetime of the login cookie?

**Comment by YanLiang1102** [comment]
let me try to tackle this @cegme

**Comment by YanLiang1102** [comment]
@cegme  
![image](https://cloud.githubusercontent.com/assets/10291607/22413309/6b992b8e-e67c-11e6-9b9a-c2056b8a5aba.png)
it only has a connection cookie and its life span is session.
I am not sure what is the problem, might be just server stop working since why the click the commit, the server does not check their crendential (in the current implementation) it is basically just make a post request to the server. So the user cookie should not be a problem. 
And based on what Manar said it is random like 30 mins and 1 hour , 2 hour something I Guess at that time server is down?
@Manar  how can the student tell the nouns not getting saved?

**Comment by manarlandis** [comment]
@YanLiang1102 coders had access to "Most Recent Activities", which they checked periodically to make sure that their work was saved. Coders also had interruption in access to this feature "Most Recent Activities". Since I had access to "Flagged Summary", I was able to see that their "verb" coding was not saved.

**Comment by manarlandis** [comment]
@YanLiang1102   I just checked interface: 
1- Coders still can't save "nouns" since it does not show on "Most Recent Activities"
2- Nouns also are not showing on "Flagged Summary"
Last saved nouns were saved yesterday. No nouns were saved when I tested the site today, but verbs were saved where I could see them on both "Most Recent Activities" and "Flagged Summary"

**Comment by manarlandis** [comment]
@YanLiang1102 After trying several possibilities, I found out that interface does not save nouns when "NA" was added when no date was needed. This is **priority** to look into because I need to give coders instructions on what to use in case no date is needed, so they can keep coding.

**Comment by ahalterman** [comment]
So the nouns are saved when NA is not included in the date? If so, it sounds like top priority is #105 so the coders can put in the correct dates.

**Comment by manarlandis** [comment]
Yes, when I tested interface, nouns were saved when I left date empty. Agree on priority to #105

**Comment by ahalterman** [comment]
Okay, I'll close this issue since all the effort now should be on #105 (making the interface handle NAs in the date)
