### ISSUE TITLE
Fix problem with date picker

### ISSUE THREAD

**Issue by ahalterman** [oudalab/fajita#72]
If the date field is left blank, it uses the last entered date. Is there a way to mark "no start date" or "no end date"? We use greater than/less than dates a lot in the dictionaries and it would be good to have a way of marking them explicitly.

**Comment by PTB-OEDA** [comment]
Default should be either "no-date" or the "current-date" so we can process relative to the coding decision.  Users should be looking up and confirming dates, which is not what I saw in this video: https://www.youtube.com/watch?v=k_s6Zd-v-2g&feature=youtu.be

A willing to be a stickler about any date convos since I do time series and have lots of preferences about how we represent dates.

**Comment by ahalterman** [comment]
All dates are formatted for CAMEO (YYYYMMDD) and the default is no date (the issue is just with the date picker in the interface).

What do you mean "confirming dates"? Since students are doing this with Arabic, they'll primarily be looking up and entering dates for new actors since there aren't existing entries to confirm.

**Comment by ahalterman** [comment]
Same as #105
